export const ActionTypes = {
  GET_BROWSER_LOCATION_SUCCESS: "GET_BROWSER_LOCATION_SUCCESS",
  GET_BROWSER_LOCATION_FAILED: "GET_BROWSER_LOCATION_FAILED",
  UPDATE_LOCATION: "UPDATE_LOCATION"
};

interface getBrowserLocationSuccess {
  type:
}